// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbUpdateUserRequest userspb update user request
//
// swagger:model userspbUpdateUserRequest
type UserspbUpdateUserRequest struct {

	// bio
	Bio string `json:"bio,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// image
	Image string `json:"image,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this userspb update user request
func (m *UserspbUpdateUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb update user request based on context it is used
func (m *UserspbUpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbUpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbUpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res UserspbUpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
