// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbAuthorizeUserRequest userspb authorize user request
//
// swagger:model userspbAuthorizeUserRequest
type UserspbAuthorizeUserRequest struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this userspb authorize user request
func (m *UserspbAuthorizeUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb authorize user request based on context it is used
func (m *UserspbAuthorizeUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbAuthorizeUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbAuthorizeUserRequest) UnmarshalBinary(b []byte) error {
	var res UserspbAuthorizeUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
