apiVersion: v1
kind: ConfigMap
metadata:
  name: depot-configuration
  labels:
    app: depot
data:
  POSTGRES_DRIVER: pgx
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_USER: depot_user
  POSTGRES_DB_NAME: depot
  POSTGRES_PASSWORD: depot_pass
  POSTGRES_SEARCH_PATH: depot,public
  HTTP_SERVER_PORT: "8080"
  GRPC_SERVER_PORT: "9000"
  GRPC_STORE_CLIENT_ADDR: depot
  GRPC_STORE_CLIENT_PORT: "9000"
  EVENT_SERVER_TYPE: nats
  NATS_URL: nats-service:4222
  OTEL_SERVICE_NAME: depot
  OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317


  SECRET_KEY: dddsdffffffalkjwiothgsfysdfwFDSFQW
  
  # GRPC_SERVER_PORT: 5080

  # KAFKA_BROKERS=kafka:9092


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depot-deployment
  labels:
    app: depot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depot
  template:
    metadata:
      labels:
        app: depot
    spec:
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
        - name: init-nats
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup nats-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nats; sleep 2; done"]

      containers:
        - name: depot
#          image: nginx:1.16
          image: reza879/depot:latest
          # image: willfarrell/ping:latest
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: depot-configuration
          ports:
            # - containerPort: 5080
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: grpc
              protocol: TCP
              containerPort: 9000

          # env:
          #   - name: HTTP_SERVER_PORT
          #     value: '5080'
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
          #     httpHeaders:
          #       - name: Custom-Header
          #         value: Awesome
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: depot-service
  labels:
    app: depot
spec:
  selector:
    app: depot
  # type: NodePort
  # session_affinity: ClientIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30004
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000
      # nodePort: 30005

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depot-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hello-worldapp.com
      http:
        paths:
          - path: /depot-spec/
            pathType: Prefix
            backend:
              service:
                name: depot-service
                port:
                  number: 8080        
          - path: /v1/api/depot/
            pathType: Prefix
            backend:
              service:
                name: depot-service
                port:
                  number: 8080
