### Create Store
curl -X 'POST' \
  'http://localhost:8080/v1/api/stores/create_store' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "Store ABC",
  "location": "The mall"
}
'
{
  "id": "dba71564-f99f-473b-ace0-2059455312d5"
}
### Create Product
curl -X 'POST' \
  'http://localhost:8080/v1/api/stores/add_product' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "storeId": "dba71564-f99f-473b-ace0-2059455312d5",
  "name": "Product ABC",
  "description": "Product description",
  "sku": "productABC",
  "price": 9.99
}
'
{
  "id":"2b645f11-0c89-44dc-9ea4-47ec0daa82a1"
}

### Register User
curl -X 'POST' \
  'http://localhost:8080/v1/register_user' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "user_abc",
  "password": "user_abc",
  "email": "user_abc",
  "bio": "user_abc",
  "image": "user_abc"
}'
{
  "id":"e6415399-fcd5-4560-b04b-24ab72c1f617"
}

### Start Basket
curl -X 'POST' \
  'http://localhost:8080/v1/api/baskets/start_basket' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "userId": "e6415399-fcd5-4560-b04b-24ab72c1f617"
}'
{
    "id":"180b75b7-9669-4adc-ba7f-c68648f730be"
}
### Add Items
curl -X 'POST' \
  'http://localhost:8080/v1/api/baskets/add_item' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "180b75b7-9669-4adc-ba7f-c68648f730be",
  "productId": "8175bcf8-c18c-438d-a69f-62ae9633b5b1",
  "quantity": 5
}'

### Create Payment
curl -X 'POST' \
  'http://localhost:8080/v1/api/payments/authorize_payment' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "userId": "e6415399-fcd5-4560-b04b-24ab72c1f617",
  "amount": 200
}'
{
  "id":"abbac81f-a128-4d23-a2b8-85fb023d5682"
}# payment id

### Checkout Basket
curl -X 'POST' \
  'http://localhost:8080/v1/api/baskets/checkout_basket' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "180b75b7-9669-4adc-ba7f-c68648f730be",
  "paymentId": "abbac81f-a128-4d23-a2b8-85fb023d5682"
}'