version: "3.8"

services:
  users:
    container_name: users
    hostname: users
    image: mallbots-users
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: users
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      OTEL_SERVICE_NAME: users
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: users_user
      POSTGRES_DB_NAME: users
      POSTGRES_PASSWORD: users_pass
      POSTGRES_SEARCH_PATH: users,public

    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  baskets:
    container_name: baskets
    hostname: baskets
    image: mallbots-baskets
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: baskets
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      OTEL_SERVICE_NAME: baskets
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      # PG_CONN: host=postgres dbname=baskets user=baskets_user password=baskets_pass search_path=baskets,public
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: baskets_user
      POSTGRES_DB_NAME: baskets
      POSTGRES_PASSWORD: baskets_pass
      POSTGRES_SEARCH_PATH: baskets,public

    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  notifications:
    container_name: notifications
    hostname: notifications
    image: mallbots-notifications
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: notifications
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      OTEL_SERVICE_NAME: notifications
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      # PG_CONN: host=postgres dbname=baskets user=baskets_user password=baskets_pass search_path=baskets,public
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: notifications_user
      POSTGRES_DB_NAME: notifications
      POSTGRES_PASSWORD: notifications_pass
      POSTGRES_SEARCH_PATH: notifications,public

    depends_on:
      - nats
      - postgesql
      - collector
      - mongodb 
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  stores:
    container_name: stores
    hostname: stores
    image: mallbots-stores
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: stores
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      OTEL_SERVICE_NAME: stores
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB_NAME: stores
      POSTGRES_PASSWORD: postgres

    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  search:
    container_name: search
    hostname: search
    image: mallbots-search
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: search
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_USER_CLIENT_ADDR: users
      GRPC_USER_CLIENT_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      NATS_STREAM: mallbots
      OTEL_SERVICE_NAME: search
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: search_user
      POSTGRES_DB_NAME: search
      POSTGRES_PASSWORD: search_pass
      POSTGRES_SEARCH_PATH: search,public
    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  payments:
    container_name: payments
    hostname: payments
    image: mallbots-payments
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: payments
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      OTEL_SERVICE_NAME: payments
      NATS_STREAM: mallbots
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB_NAME: payments
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  ordering:
    container_name: ordering
    hostname: ordering
    image: mallbots-ordering
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: ordering
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      NATS_STREAM: mallbots
      OTEL_SERVICE_NAME: ordering
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB_NAME: ordering
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  depot:
    container_name: depot
    hostname: depot
    image: mallbots-depot
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: depot
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      GRPC_STORE_CLIENT_ADDR: stores
      GRPC_STORE_CLIENT_PORT: 9000
      EVENT_SERVER_TYPE: nats
      OTEL_SERVICE_NAME: depot
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      NATS_STREAM: mallbots
      NATS_URL: nats:4222
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB_NAME: depot
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  cosec:
    container_name: cosec
    hostname: cosec
    image: mallbots-cosec
    build:
      context: .
      dockerfile: docker/Dockerfile.microservices
      args:
        service: cosec
    expose:
      - '9000'
    environment:
      ENVIRONMENT: development
      HTTP_SERVER_PORT: 8080
      GRPC_SERVER_PORT: 9000
      EVENT_SERVER_TYPE: nats
      NATS_URL: nats:4222
      NATS_STREAM: mallbots
      OTEL_SERVICE_NAME: cosec
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317
      POSTGRES_DRIVER: pgx
      POSTGRES_HOST: microservice_postgesql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB_NAME: cosec
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nats
      - postgesql
      - collector
    networks: [ "microservice" ]
    # profiles: [ microservices ]
    command: [ "./wait-for", "microservice_postgesql:5432", "--", "/mallbots/service" ]

  reverse-proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - './docker/nginx.conf:/etc/nginx/nginx.conf'
    # profiles: [ microservices ]
    depends_on:
      - ordering
      - stores
      - baskets
      - payments
      - users
      - search
      - notifications
    networks: [ "microservice" ]

  postgesql:
    image: postgres:12-alpine
    container_name: microservice_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      # - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=microservice
    volumes:
      - pgdata9:/var/lib/postgresql/data
      - ./docker/database:/docker-entrypoint-initdb.d
    networks: [ "microservice" ]
    # profiles: [ microservices ]

  jaeger:
    container_name: microservice_jaeger
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    hostname: microservice_jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks: [ "microservice" ]
    # profiles: [ microservices ]

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: microservice_prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus-config.yml
    volumes:
      - ./docker/prometheus/prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    networks: [ "microservice" ]
    # profiles: [ microservices ]    
#  node_exporter:
#    container_name: node_exporter_container
#    restart: always
#    image: prom/node-exporter
#    ports:
#      - '9101:9100'
#    networks: [ "microservices" ]

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:9.0.9
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks: [ "microservice" ]

  nats:
    container_name: nats
    hostname: nats
    image: nats:2-alpine
    ports:
      - '4222:4222'
      - '8222:8222'
    command:
      - -js
      - -sd
      - /var/lib/nats/data
      - -m 
      - '8222'
    volumes:
      - 'jsdata:/var/lib/nats/data'
    networks: [ "microservice" ]
    # profiles: [ microservices ]

  collector:
    container_name: collector
    hostname: collector
    image: otel/opentelemetry-collector-contrib:0.60.0
    command: [
      "--config=/etc/otel-config.yml",
    ]
    volumes:
      - ./docker/otel/otel-config.yml:/etc/otel-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
  #      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - jaeger

    networks: [ "microservice" ]
    # profiles: [ microservices ]

  zoo1:
    image: zookeeper:3.4.9
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - zoo_volumes:/data
      - zoo_volumes:/datalog
    networks: [ "microservice" ]

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-kafka}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-kafka}
    volumes:
      - kafka_volumes:/var/lib/kafka/data
    depends_on:
      - zoo1
    networks: [ "microservice" ]
  
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: notifications
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks: [ "microservice" ]

volumes:
  pgdata9:
  jsdata:
  kafka_volumes:
  zoo_volumes:
  mongodb_data:


networks:
  microservice:
    name: microservice
