// Code generated by go-swagger; DO NOT EDIT.

package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rezaAmiri123/microservice/payments/paymentsclient/models"
)

// NewConfirmPaymentParams creates a new ConfirmPaymentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConfirmPaymentParams() *ConfirmPaymentParams {
	return &ConfirmPaymentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConfirmPaymentParamsWithTimeout creates a new ConfirmPaymentParams object
// with the ability to set a timeout on a request.
func NewConfirmPaymentParamsWithTimeout(timeout time.Duration) *ConfirmPaymentParams {
	return &ConfirmPaymentParams{
		timeout: timeout,
	}
}

// NewConfirmPaymentParamsWithContext creates a new ConfirmPaymentParams object
// with the ability to set a context for a request.
func NewConfirmPaymentParamsWithContext(ctx context.Context) *ConfirmPaymentParams {
	return &ConfirmPaymentParams{
		Context: ctx,
	}
}

// NewConfirmPaymentParamsWithHTTPClient creates a new ConfirmPaymentParams object
// with the ability to set a custom HTTPClient for a request.
func NewConfirmPaymentParamsWithHTTPClient(client *http.Client) *ConfirmPaymentParams {
	return &ConfirmPaymentParams{
		HTTPClient: client,
	}
}

/*
ConfirmPaymentParams contains all the parameters to send to the API endpoint

	for the confirm payment operation.

	Typically these are written to a http.Request.
*/
type ConfirmPaymentParams struct {

	// Body.
	Body *models.PaymentspbConfirmPaymentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the confirm payment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmPaymentParams) WithDefaults() *ConfirmPaymentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the confirm payment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmPaymentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the confirm payment params
func (o *ConfirmPaymentParams) WithTimeout(timeout time.Duration) *ConfirmPaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the confirm payment params
func (o *ConfirmPaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the confirm payment params
func (o *ConfirmPaymentParams) WithContext(ctx context.Context) *ConfirmPaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the confirm payment params
func (o *ConfirmPaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the confirm payment params
func (o *ConfirmPaymentParams) WithHTTPClient(client *http.Client) *ConfirmPaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the confirm payment params
func (o *ConfirmPaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the confirm payment params
func (o *ConfirmPaymentParams) WithBody(body *models.PaymentspbConfirmPaymentRequest) *ConfirmPaymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the confirm payment params
func (o *ConfirmPaymentParams) SetBody(body *models.PaymentspbConfirmPaymentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ConfirmPaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
