// Code generated by mockery v2.24.0. DO NOT EDIT.

package app

import mock "github.com/stretchr/testify/mock"

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

type mockConstructorTestingTNewMockQueries interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockQueries(t mockConstructorTestingTNewMockQueries) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
