apiVersion: v2
appVersion: 1.0.0
name: mallbot
description: Helm chart for running mallbot
version: 1.0.0


dependencies:
  # - name: postgresql
  #   version: '^11'
  #   repository: https://charts.bitnami.com/bitnami
  #   # version: 11.1.3
  #   condition: postgresql.enabled
  - name: nats
    version: "^7"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: nats.enabled
  # - name: nats
  #   version: "1.0.0-beta.7"
  #   repository: https://nats-io.github.io/k8s/helm/charts/
  #   condition: nats.enabled
