// Code generated by mockery v2.27.1. DO NOT EDIT.

package notificationspb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeNotificationsServiceServer is an autogenerated mock type for the UnsafeNotificationsServiceServer type
type MockUnsafeNotificationsServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedNotificationsServiceServer provides a mock function with given fields:
func (_m *MockUnsafeNotificationsServiceServer) mustEmbedUnimplementedNotificationsServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeNotificationsServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeNotificationsServiceServer creates a new instance of MockUnsafeNotificationsServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeNotificationsServiceServer(t mockConstructorTestingTNewMockUnsafeNotificationsServiceServer) *MockUnsafeNotificationsServiceServer {
	mock := &MockUnsafeNotificationsServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
