apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      # initContainers:
      #   - name: init-mydb
      #     image: busybox:1.28
      #     command: [ 'sh', '-c', "until nslookup postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done" ]
      containers:
        - name: api
#          image: nginx:1.16
          image: reza879/service_api:9e86266
          envFrom:
          - configMapRef:
              name: api-configuration
          ports:
            - containerPort: 8080
          # env:
          #   - name: HTTP_SERVER_PORT
          #     value: '5080'
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          #     httpHeaders:
          #       - name: Custom-Header
          #         value: Awesome
          #   initialDelaySeconds: 10
          #   periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
