apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configuration
  labels:
    app: api
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: microservice_finance
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  SECRET_KEY: dddsdffffffalkjwiothgsfysdfwFDSFQW
  HTTP_KEEP_ALIVE_SERVER_HOST_PORT: :8002

  GRPC_USER_CLIENT_ADDR: user-service
  GRPC_USER_CLIENT_PORT: '5080'

  GRPC_FINANCE_CLIENT_ADDR: finance-service
  GRPC_FINANCE_CLIENT_PORT: '6080'
  # GRPC_SERVER_PORT: 5080

  # KAFKA_BROKERS=kafka:9092


