apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
  labels:
    app: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done" ]
      containers:
        - name: finance
#          image: nginx:1.16
          image: reza879/service_finance:5ef5212
          envFrom:
          - configMapRef:
              name: finance-configuration
          ports:
            - containerPort: 6080
          # env:
          #   - name: HTTP_SERVER_PORT
          #     value: '5080'
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          #     httpHeaders:
          #       - name: Custom-Header
          #         value: Awesome
          #   initialDelaySeconds: 10
          #   periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  labels:
    app: finance
spec:
  selector:
    app: finance
  type: NodePort
  ports:
    - protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 30002
