apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-configuration
  labels:
    app: finance
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: microservice_finance
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  SECRET_KEY: dddsdffffffalkjwiothgsfysdfwFDSFQW
  
  # GRPC_SERVER_PORT: 5080

  # KAFKA_BROKERS=kafka:9092


