apiVersion: v1
kind: ConfigMap
metadata:
  name: message-configuration
  labels:
    app: message
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: microservice_message
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  SECRET_KEY: dddsdffffffalkjwiothgsfysdfwFDSFQW
  HTTP_KEEP_ALIVE_SERVER_HOST_PORT: :8002

  KAFKA_BROKERS: kafka:9092
  KAFKA_GROUP_ID: message_microservice_consumer
  KAFKA_INIT_TOPICS: 'true'
  # GRPC_SERVER_PORT: 5080

  # KAFKA_BROKERS=kafka:9092


