// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorespbRebrandStoreRequest storespb rebrand store request
//
// swagger:model storespbRebrandStoreRequest
type StorespbRebrandStoreRequest struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this storespb rebrand store request
func (m *StorespbRebrandStoreRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storespb rebrand store request based on context it is used
func (m *StorespbRebrandStoreRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorespbRebrandStoreRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorespbRebrandStoreRequest) UnmarshalBinary(b []byte) error {
	var res StorespbRebrandStoreRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
