// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorespbGetStoreRequest storespb get store request
//
// swagger:model storespbGetStoreRequest
type StorespbGetStoreRequest struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this storespb get store request
func (m *StorespbGetStoreRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storespb get store request based on context it is used
func (m *StorespbGetStoreRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorespbGetStoreRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorespbGetStoreRequest) UnmarshalBinary(b []byte) error {
	var res StorespbGetStoreRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
