// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StorespbGetCatalogRequest storespb get catalog request
//
// swagger:model storespbGetCatalogRequest
type StorespbGetCatalogRequest struct {

	// store Id
	StoreID string `json:"storeId,omitempty"`
}

// Validate validates this storespb get catalog request
func (m *StorespbGetCatalogRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storespb get catalog request based on context it is used
func (m *StorespbGetCatalogRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StorespbGetCatalogRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorespbGetCatalogRequest) UnmarshalBinary(b []byte) error {
	var res StorespbGetCatalogRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
