global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: users
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'users:8080'
  - job_name: baskets
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'baskets:8080'
  - job_name: stores
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'stores:8080'
  - job_name: otel
    static_configs:
      - targets:
          - 'collector:9464'
  - job_name: otel-collector
    static_configs:
      - targets:
          - 'collector:s'
