name: Baskets

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

env:
  SERVICE: baskets

jobs:
  call-workflow:
    uses: ./common.yml
