name: Baskets

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

# env:
#   SERVICE: baskets

jobs:
  test_call:
    uses: ./.github/workflows/test/test.yml
    with:
      service: baskets
    secrets: inherit
  build_call:
    uses: ./.github/workflows/build/build.yml
    needs: test_call
    with:
      service: baskets
    secrets: inherit