name: Baskets

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

# env:
#   SERVICE: baskets

jobs:
  test_call:
    strategy:
      max-parallel: 2
      matrix:
        services: [baskets, ordering]
    uses: ./.github/workflows/workflow-1.yaml
    with:
      service: ${{ matrix.services }}
    secrets: inherit
  
  # docker_image:
  #   strategy:
  #     matrix:
  #       services: [baskets, ordering]
  #   uses: ./.github/workflows/docker.yaml
  #   # needs: test_call
  #   with:
  #     service: ${{ matrix.services }}
  #   secrets: inherit
