name: Baskets

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

# env:
#   SERVICE: baskets

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      service: baskets
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yml
    needs: test
    with:
      service: baskets
    secrets: inherit