name: Baskets

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

# env:
#   SERVICE: baskets

jobs:
  workflow_call:
    strategy:
      matrix:
        services: [baskets, ordering]
    uses: ./.github/workflows/common.yaml
    with:
      service: ${{ matrix.services }}
    secrets: inherit
