name: main

on:
  push:
    branches: [ "main", "github" ]
    # paths:
    #   - baskets/**
    #   - internal/**
    #   - stores/storespb/**

# env:
#   SERVICE: baskets

jobs:
  test:
    strategy:
      # max-parallel: 2
      matrix:
        # services: [baskets, cosec, depot, notifications, ordering, payments, search, stores, users]
        services: [baskets, users, stores]
    uses: ./.github/workflows/test.yml
    with:
      service: ${{ matrix.services }}
    secrets: inherit
  build:
    strategy:
      # max-parallel: 2
      matrix:
        # services: [baskets, cosec, depot, notifications, ordering, payments, search, stores, users]
        services: [baskets, users, stores]
    uses: ./.github/workflows/build.yml
    needs: test
    with:
      service: ${{ matrix.services }}
    secrets: inherit