name: Reusable test 

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    # env:
    #   SERVICE:
    #     required: true
    #     type: string

jobs:
  reusable_test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        working-directory: ./${{ inputs.service }}
        run: |
          # go mod download
          # go mod tidy
          # go test --cover ./...
          services=( pkg baskets cosec depot notifications ordering payments search stores users testing )
          for service in "${services[@]}"
          do
            echo "${service}"
            # do something on $service #
            cd "${service}"
            go test --cover ./...
            cd ..
          done
  